### ISSUE TITLE
undefined is not an object (evaluating 'RNFetchBlob.DocumenDir

### ISSUE THREAD

**Issue by Heverson** [HCL-HO/react-native-fetch-blob-expo#1]
This error continues, even doing the react-native-fetch-blob-expo import, did you have any fixes?
![85003](https://user-images.githubusercontent.com/729786/39328524-ffddb806-4971-11e8-8dd1-c81f415295cf.jpg)

**Comment by HCL-HO** [comment]
Sorry for late reply, I am using expo sdk 22 and it is working fine for me.

Please make sure you have link your project correctly
